# Generated by Django 3.2.7 on 2021-09-14 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_profile_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='birthday',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
