# Generated by Django 3.2.7 on 2021-09-15 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='astrological_sign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='current_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='drinking',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='favorite_bar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='favorite_restaurant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='height',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='hometown',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='interests_hobbies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='kids',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='photo',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='politics',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='sexual_orientation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='smoking',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
