# Generated by Django 3.2.7 on 2021-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210915_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
    ]
