# Generated by Django 3.2.7 on 2021-09-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profiles_covid_vaccination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='covid_vaccination_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
